apiVersion: v1
kind: Pod
metadata:
  name: release-nginx
  labels:
    app: release-nginx
spec:
  containers:
  - name: nginx
    image: paresh28/cloudethix_release_nginx_paresh:v1
    ports:
    - containerPort: 80
